# Generated by Django 5.1.6 on 2025-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Services_Images')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
